/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CompanyManager;

import Business.Company.Company;
import Business.Ecosystem;
import Business.NGO.NGODirectory;
import Business.UserAccount.UserAccount;
import Business.Volunteer.Volunteer;
import Business.Volunteer.VolunteerDirectory;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sarveshzeke
 */
public class RequestVolunteerPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestVolunteerPanel
     */
    JPanel container;
    UserAccount ua;
    Date date;
    Ecosystem ecosystem;
    VolunteerDirectory vd;
    NGODirectory ngodir;
    Volunteer volunteer;
    SimpleDateFormat date1 =  new SimpleDateFormat("HH:mm");
    SimpleDateFormat date2 =  new SimpleDateFormat("dd/MM/yyyy");
    
    public RequestVolunteerPanel(JPanel container,UserAccount ua,Ecosystem ecosystem) {
        initComponents();
        this.container = container;
        this.ecosystem = ecosystem;
        this.ua = ua;
        vd = ecosystem.getEnterpriseDirectory().getVolunteerDirectory();
        ngodir = ecosystem.getEnterpriseDirectory().getNGODirectory();
        populatecombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        designationcmbbx = new javax.swing.JComboBox<>();
        volunteercmbbx = new javax.swing.JComboBox<>();
        timecmbbx = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        datetf = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(designationcmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 113, 206, 36));

        add(volunteercmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 185, 206, -1));

        add(timecmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 346, 206, -1));

        jButton1.setText("View Slots");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 345, -1, -1));

        jLabel1.setText("Get Designation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 122, -1, -1));

        jLabel2.setText("Select Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 280, -1, -1));

        jLabel3.setText("Select Time");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 350, -1, -1));

        jLabel4.setText("Get Volunteer");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 189, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton3.setText("Request Volunteer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 421, -1, -1));
        add(datetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.show(container,"companyManager");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ArrayList<Date> timeslots = new ArrayList<Date>();
        String designation = (String) designationcmbbx.getSelectedItem();
        ArrayList<Volunteer> volunteerslist  = vd.getvolunteersByDesignation(designation);
        String date =date2.format(datetf.getDate());
        for(Volunteer v: volunteerslist)
        {
           if(v.getvolunteerName().equals((String)volunteercmbbx.getSelectedItem())){}
           try {
               v.setDate(date2.parse(date));
           } catch (ParseException ex) {
               Logger.getLogger(RequestVolunteerPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
        try {
            timeslots = vd.getAvailbleSlots(date2.parse(date),(String) volunteercmbbx.getSelectedItem());
            
        } catch (ParseException ex) {
           ex.printStackTrace();
        }
       DefaultComboBoxModel df = new DefaultComboBoxModel();
          
        for(Date d: timeslots)
        {
            df.addElement(date1.format(d));
        }
        timecmbbx.setModel(df);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Volunteer volunteer = vd.getVolunteer((String)volunteercmbbx.getSelectedItem());
      Company company = ngodir.getCompany(ua);
      String date = date2.format(datetf.getDate());
      try{
      vd.requestVolunteer(date2.parse(date), date1.parse((String)timecmbbx.getSelectedItem()), volunteer,company);
      }
      catch(ParseException e)
              {
                  
              }
         JOptionPane.showMessageDialog(this, "Appointment Scheduled");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void populatecombo() {
        
        ArrayList<Volunteer> volunteers = vd.getVolunteers();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        int flag=0;
        for(Volunteer v: volunteers)
        {
       
           for(int i=0;i<df.getSize();i++){
               if(df.getElementAt(i).equals(v))
               {
                   flag=1;
                   break;
               }   
             }
           if(flag == 0)
               df.addElement(v.getvolunteerDesignation());
           
        }
        designationcmbbx.setModel(df);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser datetf;
    private javax.swing.JComboBox<String> designationcmbbx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> timecmbbx;
    private javax.swing.JComboBox<String> volunteercmbbx;
    // End of variables declaration//GEN-END:variables
}
