/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CompanyManager;

import Business.Company.Company;
import Business.Ecosystem;
import Business.NGO.NGODirectory;
import Business.Sponsor.Sponsor;
import Business.Sponsor.SponsorDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class SponsorOfferedPanel extends javax.swing.JPanel {

    /**
     * Creates new form SponsorOfferedPanel
     */
    JPanel container;
    Ecosystem ecosystem;
    UserAccount ua;
    SponsorDirectory sponsordir;
    Company company;
    NGODirectory ngodir;
    public SponsorOfferedPanel(JPanel container,UserAccount ua,Ecosystem ecosystem) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.ecosystem = ecosystem;
        ngodir = ecosystem.getEnterpriseDirectory().getNGODirectory();
        sponsordir = ecosystem.getEnterpriseDirectory().getSponsorDirectory();
        company = ngodir.getCompany(ua);
        populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sponsorreqtbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sponsorreqtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sponsor", "Offered Amount"
            }
        ));
        jScrollPane1.setViewportView(sponsorreqtbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 34, -1, -1));

        jButton1.setText("Accept Sponsor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, -1));

        jButton2.setText("Decline Sponsor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) sponsorreqtbl.getModel();
        int selectedRow = sponsorreqtbl.getSelectedRow();
        if(selectedRow == -1) {JOptionPane.showMessageDialog(this, "Please Select a sponsor and proceed");return;}
        String sponsorname = df.getValueAt(selectedRow,0).toString();
        int amount = Integer.parseInt(df.getValueAt(selectedRow,1).toString());
        sponsordir.sponsorToCompany(sponsorname, amount, company);
        company.addBudget(amount);
        populatetable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) sponsorreqtbl.getModel();
        int selectedRow = sponsorreqtbl.getSelectedRow();
        if(selectedRow == -1) {JOptionPane.showMessageDialog(this, "Please Select a sponsor and proceed");return;}
        String sponsorname = df.getValueAt(selectedRow,0).toString();
        Sponsor sponsor = sponsordir.getSponsor(sponsorname);
        HashMap<Company,String> offerStatus = sponsor.getOfferStatus();
        offerStatus.put(company, "Declined");
         populatetable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.show(container,"companyManager");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sponsorreqtbl;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        
         DefaultTableModel df = (DefaultTableModel) sponsorreqtbl.getModel();
        df.setRowCount(0);
        ArrayList<Sponsor> sponsors = sponsordir.getSponsorsDirectory();
        HashMap<Company,Integer> offer;
        HashMap<Company,String> offerStatus;
        for(Sponsor s:sponsors)
        {
             offer = s.getSponsoredRequests();
             offerStatus = s.getOfferStatus();
             for(Company t : offer.keySet())
             {
                 if(t.equals(company) && offerStatus.get(t).equals("Requested"))
                 {
                     String[] row = {s.getSponsorName(),String.valueOf(offer.get(t))};
                     df.addRow(row);
                 }
             }
        }
        
        sponsorreqtbl.setModel(df);
    }
    }

