/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminRole;

import Business.Ecosystem;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.Util.Utility;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class ManageUsersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUsersPanel
     */
    JPanel container;
    Ecosystem ecosystem;
    UserAccountDirectory ud;
    UserAccount users;
    
    public ManageUsersPanel(JPanel container,Ecosystem ecosystem) {
        
        initComponents();
        this.ecosystem = ecosystem;
        this.container = container;
        ud = ecosystem.getUserAccountDirectory();
        populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageuserstbl = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        manageuserstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Username", "Email", "Role"
            }
        ));
        jScrollPane1.setViewportView(manageuserstbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 610, 340));

        jButton2.setText("Give access");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String passcode = Utility.generatePassword();
        System.out.println("passsword is "+passcode);
        DefaultTableModel df = (DefaultTableModel) manageuserstbl.getModel();
        int selectedRow = manageuserstbl.getSelectedRow();
        if(selectedRow == -1) {JOptionPane.showMessageDialog(this, "Select user to grant access");return;}
          String username = df.getValueAt(selectedRow,1).toString();
          users = ud.getUserToGrantAccess(username);
          users.setPasscode(passcode);
          users.setPassword(passcode);
          System.out.println(passcode);
          Utility.SendEmail(users.getUsername(), passcode, users.getEmail());
          ud.provideAccess(username);
          populatetable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.show(container,"Sysadmin");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populatetable() {
        
        DefaultTableModel dt = (DefaultTableModel) manageuserstbl.getModel();
        dt.setRowCount(0);
        ArrayList<UserAccount> accessUsersList = ud.getUserAccountList();
        
        for(UserAccount ua : accessUsersList)
        {
            if(ua.getUsername().equals("sysadmin") || ua.getRole().toString().equals("Business.Role.CompanyManagerRole")) continue;
            if(ua.getAccountStatus().equals("Access requested"))
            {
            String[] row = {ua.getEmployee().getName(),ua.getUsername(),ua.getEmail(),ua.getRole().getClass().toString()};
            dt.addRow(row);
            }
        }
        manageuserstbl.setModel(dt);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageuserstbl;
    // End of variables declaration//GEN-END:variables
}
