/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.LocationManagerRole;

import Business.Company.Company;
import Business.Ecosystem;
import Business.NGO.Donation;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.UserAccount.UserAccount;
import Business.Venue.VenueDirectory;
import java.awt.CardLayout;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class ViewSchedulesDonations extends javax.swing.JPanel {

    /**
     * Creates new form ViewSchedulesDonations
     */
    JPanel container;
    Ecosystem ecosystem;
    UserAccount ua;
    VenueDirectory vd;
    NGODirectory ngodir;
    Company company;
    
    public ViewSchedulesDonations(JPanel container,Ecosystem ecosystem,UserAccount ua) {
        initComponents();
        this.container = container;
        this.ecosystem = ecosystem;
        this.ua = ua;
        vd = ecosystem.getEnterpriseDirectory().getVenueDirectory();
     //   date.setText(" "+String.valueOf(LocalTime.now().getHour()) + ":"+String.valueOf(LocalTime.now().getMinute()));
        ngodir = ecosystem.getEnterpriseDirectory().getNGODirectory();
        //populatetable();
        jLabel2.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/back.jpeg").getImage().getScaledInstance(270,260, Image.SCALE_DEFAULT)));
        jButton1.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/back.jpeg").getImage().getScaledInstance(100,50, Image.SCALE_DEFAULT)));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblschednew = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/sarveshzeke/Downloads/grad2new.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 0, 51)));
        jLabel1.setPreferredSize(new java.awt.Dimension(882, 400));

        setBackground(new java.awt.Color(255, 204, 204));
        setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblschednew.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tblschednew.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Donations", "Company", "NGO"
            }
        ));
        tblschednew.setGridColor(new java.awt.Color(51, 0, 51));
        tblschednew.setShowGrid(true);
        jScrollPane1.setViewportView(tblschednew);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 500, 170));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, 50));

        jButton2.setText("View Scheduled Donation");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/schedule.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 270, 260));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("View Schedule Donation ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 250, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"venueManager");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         NGO ngo = ngodir.getNGO(ua);
        DefaultTableModel df = (DefaultTableModel) tblschednew.getModel();
        df.setRowCount(0);
        String date,venue;
        ArrayList<Donation> donations = ngo.getDonations();
        DateFormat datef = new SimpleDateFormat("dd-MMM-yyyy"); 
        for(Donation m: donations)
        {
            if(m.getComp().equals(company))
            {
            if(m.getVenue() == null) venue = "Not Selected";
            else venue = m.getVenue().getVenueName();
            if(m.getDate() == null) date= "Not Selected";
            else date = datef.format(m.getDate());
                String[] row = {m.getComp().getCompanyName(),venue,date,m.getVenueStatus()};
                df.addRow(row);
            }
        
    }

    

        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblschednew;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
       ArrayList<NGO> ngo = ngodir.getNgolist();
        DefaultTableModel df = (DefaultTableModel) tblschednew.getModel();
        df.setRowCount(0);
        String date;
        ArrayList<Donation> donations;
        for(NGO n: ngo)
        {
           if(n.getDonations()== null) n.setDonations(new ArrayList<Donation>());
           donations = n.getDonations();
           for(Donation d: donations)
           {
               if(d.getVenue()== null) continue;
               if(d.getVenue().getUserAccount().equals(ua))
               {
                   System.out.println(d.getVenueStatus());
                   if(d.getVenueStatus().equals("Registered")){
                   DateFormat datef = new SimpleDateFormat("dd-MMM-yyyy");
                   date = datef.format(d.getDate());
                   String donation = d.getComp().getCompanyName();
                   String[] row = {date,donation,d.getComp().getUserAccount().getEmail(),n.getNGOName()};
                   df.addRow(row);}
                }
            }
        }
        tblschednew.setModel(df);
       }
    
    
    }
 
