/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SponsorRole;

import Business.Company.Company;
import Business.Ecosystem;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.Sponsor.Sponsor;
import Business.Sponsor.SponsorDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class SponsorCompaniesPanel extends javax.swing.JPanel {

    /**
     * Creates new form SponsorTeamsPanel
     */
    JPanel container;
    Ecosystem ecosystem;
    UserAccount ua;
    NGODirectory ngodir;
    SponsorDirectory sponsordir;
    public SponsorCompaniesPanel(JPanel container,UserAccount ua,Ecosystem ecosystem) {
        initComponents();
        this.container = container;
        this.ecosystem = ecosystem;
        this.ua = ua;
        ngodir = ecosystem.getEnterpriseDirectory().getNGODirectory();
        sponsordir = ecosystem.getEnterpriseDirectory().getSponsorDirectory();
        populateNGOcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ngocmbbx = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sponsortbl = new javax.swing.JTable();
        sponsortf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ngocmbbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngocmbbxActionPerformed(evt);
            }
        });
        add(ngocmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 190, -1));

        jLabel1.setText("NGO Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        sponsortbl.setBackground(new java.awt.Color(255, 153, 153));
        sponsortbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sponsortbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Company Name", "Donations Done", "Offered Amount"
            }
        ));
        jScrollPane1.setViewportView(sponsortbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 570, 150));
        add(sponsortf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 360, 40));

        jButton1.setText("Offer Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 190, 40));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/sarveshzeke/Downloads/vecteezy_background-wallpaper-with-polygons-in-gradient-colors_1218819/398128-Background_wallpaper_with_polygons_in_gradient_colors.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, -370, 5920, 3580));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"sponsorWorkArea");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ngoName = (String) ngocmbbx.getSelectedItem();
        NGO ngo = ngodir.getNGO(ngoName);
        DefaultTableModel df = (DefaultTableModel) sponsortbl.getModel();
        int selectedRow = sponsortbl.getSelectedRow();
        if(selectedRow == -1) {JOptionPane.showMessageDialog(this, "Select company");return;}
        String compName = df.getValueAt(selectedRow,0).toString();
        Company comp = ngodir.getCompany(compName,ngoName);
        
        Sponsor sponsor = sponsordir.getSponsor(ua);
        sponsordir.offerToCompany(sponsor, comp, Integer.parseInt(sponsortf.getText()));
        sponsortf.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ngocmbbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngocmbbxActionPerformed
        // TODO add your handling code here:
        String ngoName = (String) ngocmbbx.getSelectedItem();
        NGO ngo = ngodir.getNGO(ngoName);
        DefaultTableModel df = (DefaultTableModel) sponsortbl.getModel();
        df.setRowCount(0);
        ArrayList<Company> companies = ngo.getCompanyofNGo();
//        Collections.sort(companies, new Comparator<Team>() {
//            @Override
//            public int compare(Companu t1, Team t2) {
//                return t2.getMatchesWon()-t1.getMatchesWon();
//            }
//        });
        for(Company c: companies)
        {
            String[] row = {c.getCompanyName(),String.valueOf(c.getDonationsdone()),String.valueOf(c.getBudget())};
            df.addRow(row);
        }
        sponsortbl.setModel(df);
    }//GEN-LAST:event_ngocmbbxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"sponsorWorkArea");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> ngocmbbx;
    private javax.swing.JTable sponsortbl;
    private javax.swing.JTextField sponsortf;
    // End of variables declaration//GEN-END:variables

    private void populateNGOcombo() {
        
        ArrayList<NGO> ngo = ngodir.getNgolist();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        for(NGO n: ngo)
        {
            df.addElement(n.getNGOName());
        }
        ngocmbbx.setModel(df);
    }
}
